### PR TITLE
JWKS URI

### LINKED ISSUE #451: Support for JWKS URI
Currently, the AuthConfig API (v1beta2) allows specifying an [`issuerURL`](https://github.com/Kuadrant/authorino/blob/aaff7a327eb8d29e9245355b1daeb01771a07a30/api/v1beta2/auth_config_types.go#L355) from which a JWKS is discovered, using [OpenId Connect Discovery](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig). Alternatively, the documentation [mentions](https://github.com/Kuadrant/authorino/blob/aaff7a327eb8d29e9245355b1daeb01771a07a30/install/crd/authorino.kuadrant.io_authconfigs.yaml#L2595) a `jwksUrl` field that was never delivered.

To support JWT issuers that do not implement OpenId Connect Discovery, the AuthConfig API should allow specifying an alternative JWKS URL.

This will also start paving the way for Kuadrant to support [Gateway API JWT policies](https://github.com/kubernetes-sigs/gateway-api/pull/2213) in the future, which could be then fully implemented as Authorino AuthConfigs by adding support as well for JWKs stored in Kubernetes Secrets.

### LINKED ISSUE #463: Authorino accepts the JWT signed with newly created JWKS signing key even with jwt.ttl set to zero
**Describe the bug**
According to the docs (https://github.com/Kuadrant/authorino/blob/main/docs/features.md#jwt-verification-authenticationjwt) if `.jwt.ttl` is set to zero the OIDC connect discovery should be disabled. I am using Keycloak as OIDC provider. When a signing key is removed in Keycloak from JWKS and a new signing key is created in JWKS and a new JWT is created (using the new signing key) Authorino should reject (401) requests using that JWT since it should have no way of knowing about the signing key change in JWKS -> its cache should only contain the old signing key which is not good for validating JWT signed with the new signing key. However, the 200 OK response is what one gets.

It seems as if the proper signing key was used to validate the JWT despite the OIDC connect discovery being disabled. There must be some communication with Keycloak to get the new signing key somewhere -> either in Authorino itself or in the oidc library it uses under the hood.

**Help us Reproduce it**

1. Get a Keycloak instance, Realm, Client, User; get an Authorino instance; deploy some app
2. Secure you app by Authorino
3. Make sure that TTL is set to zero in Authconfig CR:
```
spec:
  rules:
    authentication:
      rhsso:
        credentials:
          authorizationHeader:
            prefix: Bearer
        jwt:
          issuerUrl: 'keycloak-url//auth/realms/your-realm-name'
          ttl: 0
        metrics: false
        priority: 0
```
4. At this point Authorino should have cached Keycloak JWKS, delete the signing key from JWKS in Keycloak
5. Create a new signing key in JWKS in Keycloak (Authorino has no way of knowing about this due to TTL being set to zero)
6. Create a new JWT (it can only be validated by new signing key)
7. Use the new JWT to access the app

**Expected behavior**

HTTP Error 401 since Authorino is not aware of signing JWK replacement since this was done after Authorino updated its cache

Instead one gets

HTTP 200 OK - it indicates that there were some communication with Keycloak to get the current signing key since the JWT was successfully validated. However, there should not be any such communication there according to the documentation

**Environment (please complete the following information):**
- Cluster information: kubernetes v1.27.9+e36e183 
- Authorino version : quay.io/kuadrant/authorino:latest
- Link to the Authorino `AuthConfig` resource (e.g. in some GitHub gist): see the snippet above

### PR DESCRIPTION
**Pull request by guicassolato**
Adds support for specifying a JSON Web Key Set (JWKS) URI alternatively to an issuer URI for the JWT authentication method.

Closes #451, #463

### TODOs
- [x] Bump version of [github.com/coreos/go-oidc](https://pkg.go.dev/github.com/coreos/go-oidc/v3) to v3
- [x] `spec.authentication.jwt.jwskUrl`
- [x] `spec.metadata.userInfo.userInfoUrl` - alternative to `spec.metadata.userInfo.identitySource` which requires mapping to a `spec.authentication.jwt.issuerUrl`, but won't work with `.jwskUrl`
- [x] Clarify in the docs about `spec.authentication.jwt.ttl` as related to the openid config only, not the jwks – closes #463
- [x] Tests

### Verification steps

```sh
make local-setup TLS_ENABLED=false DEPLOY_KEYCLOAK=true FF=1
```

```sh
kubectl port-forward deployment/envoy 8000:8000 2>&1 >/dev/null &
```

```sh
kubectl apply -f -<<EOF
apiVersion: authorino.kuadrant.io/v1beta3
kind: AuthConfig
metadata:
  name: oidc
spec:
  hosts:
  - talker-api.oidc.127.0.0.1.nip.io
  authentication:
    keycloak:
      jwt:
        issuerUrl: http://keycloak:8080/realms/kuadrant
  metadata:
    userinfo:
      userInfo:
        identitySource: keycloak
  response:
    success:
      headers:
        x-user-email:
          plain:
            expression: auth.metadata.userinfo.email
---
apiVersion: authorino.kuadrant.io/v1beta3
kind: AuthConfig
metadata:
  name: jwks
spec:
  hosts:
  - talker-api.jwks.127.0.0.1.nip.io
  authentication:
    keycloak:
      jwt:
        jwksUrl: http://keycloak:8080/realms/kuadrant/protocol/openid-connect/certs
  metadata:
    userinfo:
      userInfo:
        userInfoUrl: http://keycloak:8080/realms/kuadrant/protocol/openid-connect/userinfo
  response:
    success:
      headers:
        x-user-email:
          plain:
            expression: auth.metadata.userinfo.email
EOF
```

```sh
ACCESS_TOKEN=$(kubectl run token --attach --rm --restart=Never -q --image=curlimages/curl -- http://keycloak:8080/realms/kuadrant/protocol/openid-connect/token -s -d 'grant_type=password' -d 'client_id=demo' -d 'username=john' -d 'password=p' -d 'scope=openid' | jq -r .access_token)
```

```sh
curl -H "Authorization: Bearer $ACCESS_TOKEN" http://talker-api.oidc.127.0.0.1.nip.io:8000/hello
# 200
```

```sh
curl -H "Authorization: Bearer $ACCESS_TOKEN" http://talker-api.jwks.127.0.0.1.nip.io:8000/hello
# 200
```

### CODE REVIEW

File: api/v1beta3/auth_config_types.go [hunk 1]
```diff
@@ -358,17 +358,26 @@ type ApiKeyAuthenticationSpec struct {
...
+//	+kubebuilder:validation:XValidation:rule="!(has(self.jwksUrl) && self.jwksUrl != '' && has(self.issuerUrl) && self.issuerUrl != '')",message="Use one of: jwksUrl, issuerUrl"
 type JwtAuthenticationSpec struct {
-	// URL of the issuer of the JWT.
-	// If `jwksUrl` is omitted, Authorino will append the path to the OpenID Connect Well-Known Discovery endpoint
-	// (i.e. "/.well-known/openid-configuration") to this URL, to discover the OIDC configuration where to obtain
-	// the "jkws_uri" claim from.
-	// The value must coincide with the value of  the "iss" (issuer) claim of the discovered OpenID Connect configuration.
+	// URL of the JSON Web Key Set (JWKS) endpoint.
+	// Use it for non-OpenID Connect (OIDC) JWT authentication, where the JWKS URL is known beforehand.
+	// The JSON Web Keys (JWK) obtained from this endpoint are automatically cached and the caching updated whenever the kid of a JWT does not match any of the cached JWKs (https://openid.net/specs/openid-connect-core-1_0.html#RotateSigKeys).
```
Comment (didierofrivia) [inline api/v1beta3/auth_config_types.go:366]: 's/kit/keys/g' (?)

Comment (didierofrivia) [reply api/v1beta3/auth_config_types.go:366]: nop, TIL: https://www.rfc-editor.org/rfc/rfc7517#section-4.5

**Review by didierofrivia — COMMENTED** [review]
Steps worked like a charm!

File: pkg/evaluators/identity/jwt.go [hunk 2]
```diff
@@ -0,0 +1,205 @@
...
+
+var tokenVerifierConfig = &oidc.Config{SkipClientIDCheck: true, SkipIssuerCheck: true}
+
+type JWTAuthentication struct {
+	auth.AuthCredentials
+
+	verifier JWTVerifier
+}
+
+func NewJWTAuthentication(ctx gocontext.Context, verifier JWTVerifier, creds auth.AuthCredentials) *JWTAuthentication {
```
[the remark this answers is not in the document]
Comment (guicassolato) [reply pkg/evaluators/identity/jwt.go:34]: Good catch. I guess I copied from `NewOIDCProviderVerifier`. Fixing it now. Thanks!

**Review by KevFan — APPROVED** [review]
Changes looks good to me 💯 

Verified steps worked as expected 🏅
