### PR TITLE
Fix phantom host association

### LINKED ISSUE #326: Phantom host association (cannot unlink host from AuthConfig)
**Describe the bug**
When I edit an AuthConfig to remove a host listed in `spec.hosts`, the removed host remains linked to the AuthConfig cache.

**Help us Reproduce it**
1. Create an `AuthConfig` such as
    ```sh
    kubectl apply -f -<<EOF
    apiVersion: authorino.kuadrant.io/v1beta1
    kind: AuthConfig
    metadata:
      name: talker-api-protection
    spec:
      hosts: ["host-1", "host-2"]
    EOF
    ```
2. Send requests to hosts `host-1` and `host-2`
    ```sh
    curl -H 'Host: host-1' http://localhost:8000 -i
    # HTTP/1.1 200 OK
    ```
    ```sh
    curl -H 'Host: host-2' http://localhost:8000 -i
    # HTTP/1.1 200 OK
    ```
3. Edit the `AuthConfig` to remove the host `host-2`
    ```sh
    kubectl apply -f -<<EOF
    apiVersion: authorino.kuadrant.io/v1beta1
    kind: AuthConfig
    metadata:
      name: talker-api-protection
    spec:
      hosts: ["host-1"]
    EOF
    ```
4. Send requests again to hosts `host-1` and `host-2`
    ```sh
    curl -H 'Host: host-1' http://localhost:8000
    # HTTP/1.1 200 OK
    ```
    ```sh
    curl -H 'Host: host-2' http://localhost:8000
    # HTTP/1.1 200 OK <===== Expected: 404
    ```
5. Notice that the `AuthConfig` was still enforced on the request to `host-2`

**Expected behavior**

After removing a host from an `AuthConfig`, the`AuthConfig` should not longer apply to requests sent to that host.

**Environment (please complete the following information):**
Authorino v0.9.0

### PR DESCRIPTION
**Pull request by guicassolato**
Delete all entries in the cache related to an AuthConfig before adding again only to hosts that apply.

Ensures hosts occasionally removed from the AuthConfig on an update are no longer linked to the AuthConfig in the cache after the reconciliation.

Closes #326.

### Verification steps

Build, deploy, setup:

```sh
make local-setup
kubectl port-forward deployment/envoy 8000:8000 &
```

Create an AuthConfig for 2 hosts:

```sh
kubectl apply -f -<<EOF
apiVersion: authorino.kuadrant.io/v1beta1
kind: AuthConfig
metadata:
  name: talker-api-protection
spec:
  hosts: ["host-1", "host-2"]
EOF
```

Send requests to the hosts:

```sh
curl -H 'Host: host-1' http://localhost:8000 -i
# HTTP/1.1 200 OK
```

```sh
curl -H 'Host: host-2' http://localhost:8000 -i
# HTTP/1.1 200 OK
```

Remove one of the hosts from the AuthConfig:

```sh
kubectl apply -f -<<EOF
apiVersion: authorino.kuadrant.io/v1beta1
kind: AuthConfig
metadata:
  name: talker-api-protection
spec:
  hosts: ["host-1"]
EOF
```

Send requests again to the hosts:

```sh
curl -H 'Host: host-1' http://localhost:8000 -i
# HTTP/1.1 200 OK
```

```sh
curl -H 'Host: host-2' http://localhost:8000 -i
# HTTP/1.1 404 Not Found
```

### CODE REVIEW

File: controllers/auth_config_controller.go [hunk 1]
```diff
@@ -93,6 +93,9 @@ func (r *AuthConfigReconciler) Reconcile(ctx context.Context, req ctrl.Request)
 			return ctrl.Result{}, err
 		}
 
+		// delete related authconfigs from cache.
+		r.Cache.Delete(cacheId)
```
Comment (guicassolato) [inline controllers/auth_config_controller.go:97]: This is the simplest solution.

Another approach would be to implement an alternate delete function that takes as input the cache key (host) instead of the cache id. We could then delete only the diff between the keys of the `evaluatorConfigByHost` and `r.Cache.FindKeys(cacheId)`.

Comment (guicassolato) [reply controllers/auth_config_controller.go]: Implemented the 2nd approach, for optimal availability while gradually updating the cache for possibly multiple hosts listed in the AuthConfig.

**Review by maleck13 — COMMENTED** [review]
code looks reasonable I have not done the verification
